#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.  Opens .sent files as sent
# presentations.  Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
 	*\.tex) pandoc "$file" -f latex -s -o "$base".pdf ;;
	*\.md) pandoc "$file" -f markdown -s -o "$base".pdf ;;
	*\.py) python "$file" ;;
esac
